{% set version = "3.10" %}

package:
  name: nsis
  version: {{ version }}

source:
  - url: http://sourceforge.net/projects/nsis/files/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}.zip
    sha256: fcdce3229717a2a148e7cda0ab5bdb667f39d8fb33ede1da8dabc336bd5ad110
    folder: binary

  - url: http://sourceforge.net/projects/nsis/files/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}-log.zip  # [win and nsis_variant == 'log_enabled']
    sha1: 4fcb221a4dc4719580f201f6399b2035073aeaaa  # [win and nsis_variant == 'log_enabled']
    folder: binary_with_logging  # [win and nsis_variant == 'log_enabled']

  - url: http://sourceforge.net/projects/nsis/files/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}-src.tar.bz2  # [unix]
    sha256: 11b54a6307ab46fef505b2700aaf6f62847c25aa6eebaf2ae0aab2f17f0cb297  # [unix]
    folder: src  # [unix]
    patches:   # [unix]
      - 0001-Always-use-relative-paths-for-CONF-and-DATA-directories.patch  # [unix]
  # Plugins
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/BgWorker-20091001.zip
    sha256: be8c5264c796309c465d017b12e12aee62d3c8c20966bbbecb96fb8fabb023ce
    folder: plugins/BgWorker
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/elevate-1.3.0-redist.7z
    sha256: b1b3f070353a0eadee2cea3a575049d10df9763ff24e39313da4cec9455382e1
    folder: plugins/elevate
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/UAC-0.2.4c-20150526.zip
    sha256: 20e3192af5598568887c16d88de59a52c2ce4a26e42c5fb8bee8105dcbbd1760
    folder: plugins/UAC
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/nsis-untgz-5c814c5f2c8a9a14e3a6ddd3e594fcc76db5b86a.zip
    sha256: ae68c41493abbb8800640acdf67a06c63bcceaaf21b539c50c348a20dc4b2803
    folder: plugins/untgz
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/nsis-UnicodePathTest-fa74caef553883f1820049d89e169aff57551796.zip
    sha256: 1a4dc09f0fbb7d6be88835c50a7c95dbd37470c65e29cf676b14e3ad9c4d7494
    folder: plugins/UnicodePathTest
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/AccessControl-1.0.8.3-20210224.zip
    sha256: 9aa60f9c5c023fda2808af216514d8913d2673bc522d944ee771da032a1bdc10
    folder: plugins/access-control

build:
  number: 0
  skip: true  # [aarch64 or ppc64le or osx]
  string: h{{ PKG_HASH }}_log_{{ PKG_BUILDNUM }}  # [nsis_variant == 'log_enabled']
  track_features:
    - nsis_log_enabled  # [nsis_variant == 'log_enabled']

requirements:
  build:
    - {{ compiler('cxx') }}  # [unix]
    - scons  # [unix]
  host:
    - zlib   # [unix]
  run:

test:
  commands:
    - makensis /VERSION          # [win]
    # echo needed to make the output of the command visible in the CI logs :shrug:
    - makensis -VERSION && echo  # [unix]

about:
  home: http://sourceforge.net/projects/nsis
  summary: Nullsoft Scriptable Install System
  license: zlib-acknowledgement AND bzip2-1.0.6 AND CPL-1.0 AND LGPL-2.1-or-later
  license_file:
    - binary/COPYING
    - plugins/UAC/License.txt
    - plugins/untgz/LICENSE.TXT
    - plugins/UnicodePathTest/Readme.txt
    # plugins/elevate has unknown license
    # plugins/BgWorker has unknown license

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - msarahan
    - patricksnape
    - jaimergp
