compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
azure:
  store_build_artifacts: false
conda_build:
  pkg_format: '2'
