appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: L9aq8F4FzlmLXiJ7Q/1LltvK79AQZxxKJYfC+viNZLO4LqdA+9o0SS15hLFWN6rSuP9cLmi0TS4ruSRnyQVcrCHMCmkDk3qlHV2Ks8QumfhoU1BIUDZk09PJmyKjotupJF0ubq/NWTCtH/PryCK/CCAzUc/QTvcTmeBXwS4tyIvdzRek8Oh9Fs/vxMwNEDeG7vfXFv3Q7flRLA5Z3rkmKlzba32Lya+an4GQRpKcBgEBDgT+U31m2Ld7NmrG1GIp6aPOIDgTfwVZeyKRwh+iO2OWq1Zhle6H7lCTAZ96LlftQkDi8UsJrzXZfK6QVECd5lfB5Z01SFLORZ+Lf+/ZBw14GwRefOz5t3v2sHMwB1daBDx/l3UuQ3dwvJUgDsarravNpaKYO/YVnRGyJvlQBvBPP3GIEkvOnO2F6oPCNRQXKDjmWWVTy0PDvAndnqG7Q7vP5EhkBvz0LIQ7IDRaMz1cJIo1CrhpIRh8fiDI3zKsRjCEEklfELdSiP3lVCUm/0xcgUt1mCv5Wg8ZChrIz7SvWztc/Ttn+INZPxkrMSgQbGTNgewZvZwhCDx2Jay4A4hxQWrvKZbUd/YnQST30DG/8+0HEJd0S8H23qtFVgEaey+NjeMwCIQ/QuVJEx3TL+hUQ1M/dydh85yQ+ckkvPMDDX4y073zGmyyny8OSHU=}
